var DISQUS=function(e){var h=e.DISQUS||{};h.AssertionError=function(b){this.message=b};h.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};h.assert=function(b,f,g){if(!b)if(g)e.console&&e.console.log("DISQUS assertion failed: "+f);else throw new h.AssertionError(f);};var b=[];h.define=function(c,f){typeof c==="function"&&(f=c,c="");for(var g=c.split("."),a=g.shift(),d=h,n=(f||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},e);a;)d=d[a]?d[a]:d[a]={},a=g.shift();for(var l in n)n.hasOwnProperty(l)&&(!n.__overwrites__&&d[l]!==null&&h.assert(!d.hasOwnProperty(l),"Unsafe attempt to redefine existing module: "+l,!0),d[l]=n[l],b.push(function(a,d){return function(){delete a[d]}}(d,l)));return d};h.use=function(b){return h.define(b)};h.cleanup=function(){for(var c=0;c<b.length;c++)b[c]()};return h}(window);
DISQUS.define(function(e,h){var b=e.DISQUS,c=e.document,f=c.getElementsByTagName("head")[0]||c.body,g={running:!1,timer:null,queue:[]};b.defer=function(a,d){function b(){var a=g.queue;if(a.length===0)g.running=!1,clearInterval(g.timer);for(var d=0,f;f=a[d];d++)f[0]()&&(a.splice(d--,1),f[1]())}g.queue.push([a,d]);b();if(!g.running)g.running=!0,g.timer=setInterval(b,100)};b.each=function(a,d){var b=a.length,f=Array.prototype.forEach;if(isNaN(b))for(var c in a)a.hasOwnProperty(c)&&d(a[c],c,a);else if(f)f.call(a,
d);else for(f=0;f<b;f++)d(a[f],f,a)};b.extend=function(a){b.each(Array.prototype.slice.call(arguments,1),function(d){for(var b in d)a[b]=d[b]});return a};b.serializeArgs=function(a){var d=[];b.each(a,function(a,b){a!==h&&d.push(b+(a!==null?"="+encodeURIComponent(a):""))});return d.join("&")};b.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};b.serialize=function(a,d,f){d&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=b.serializeArgs(d));if(f)return d=
{},d[(new Date).getTime()]=null,b.serialize(a,d);d=a.length;return a.charAt(d-1)=="&"?a.slice(0,d-1):a};b.require=function(a,d,g,h,e){function j(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))h&&h(),q&&clearTimeout(q),b.bean.remove(a.target,p,j)}var k=c.createElement("script"),p=k.addEventListener?"load":"readystatechange",q=null;k.src=b.serialize(a,d,g);k.async=!0;k.charset="UTF-8";(h||e)&&b.bean.add(k,p,j);e&&(q=setTimeout(function(){e()},2E4));f.appendChild(k);return b};
b.requireStylesheet=function(a,d,g){var h=c.createElement("link");h.rel="stylesheet";h.type="text/css";h.href=b.serialize(a,d,g);f.appendChild(h);return b};b.requireSet=function(a,d,f){var c=a.length;b.each(a,function(a){b.require(a,{},d,function(){--c===0&&f()})})};b.injectCss=function(a){var b=c.createElement("style");b.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");e.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));b.styleSheet?b.styleSheet.cssText=a:b.appendChild(c.createTextNode(a));
f.appendChild(b)}});
DISQUS.define("JSON",function(){function e(a){return a<10?"0"+a:a}function h(b){a.lastIndex=0;return a.test(b)?'"'+b.replace(a,function(a){var b=l[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function b(a,c){var g,e,j,l,k=d,m,i=c[a];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!f&&(i=i.toJSON(a));typeof o==="function"&&(i=o.call(c,a,i));switch(typeof i){case "string":return h(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";d+=n;m=[];if(Object.prototype.toString.apply(i)==="[object Array]"){l=i.length;for(g=0;g<l;g+=1)m[g]=b(g,i)||"null";j=m.length===0?"[]":d?"[\n"+d+m.join(",\n"+d)+"\n"+k+"]":"["+m.join(",")+"]";d=k;return j}if(o&&typeof o==="object"){l=o.length;for(g=0;g<l;g+=1)e=o[g],typeof e==="string"&&(j=b(e,i))&&m.push(h(e)+(d?": ":":")+j)}else for(e in i)Object.hasOwnProperty.call(i,e)&&(j=b(e,i))&&m.push(h(e)+(d?": ":":")+j);j=m.length===0?"{}":d?"{\n"+d+m.join(",\n"+d)+"\n"+
k+"}":"{"+m.join(",")+"}";d=k;return j}}var c={},f=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,n,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;c.stringify=function(a,f,c){var g;n=d="";if(typeof c==="number")for(g=0;g<c;g+=1)n+=" ";else typeof c==="string"&&(n=c);if((o=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return b("",{"":a})};c.parse=function(a,b){function f(a,
d){var c,g,e=a[d];if(e&&typeof e==="object")for(c in e)Object.hasOwnProperty.call(e,c)&&(g=f(e,c),g!==void 0?e[c]=g:delete e[c]);return b.call(a,d,e)}var d,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),
typeof b==="function"?f({"":d},""):d;throw new SyntaxError("JSON.parse");};var j={a:[1,2,3]},k,p;if(Object.toJSON&&Object.toJSON(j).replace(/\s/g,"")==='{"a":[1,2,3]}')k=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(j='{"a":[1,2,3]}'.evalJSON(),j.a&&j.a.length===3&&j.a[2]===3&&(p=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),f=!(a&&a.length===3&&a[2]===3))})();if(f||!k||!p)return{stringify:c.stringify,parse:c.parse};return{stringify:k,
parse:p}});
DISQUS.define("Bus",function(){function e(a){a=a.split("/");return a[0]+"//"+a[2]}var h=DISQUS.use("JSON"),b=window.location.hash.slice(1),c=window.opener||window.parent,f=document.referrer,g={};g.client=e(document.location.href);g.host=f?e(f):g.client;return{origins:g,messageHandler:function(a){var b;try{b=DISQUS.JSON.parse(a.data)}catch(f){return}if(!b.name||!(b.name[0]==="!"&&a.origin!==g.client))switch(b.scope){case "client":DISQUS.Bus.trigger(b.name,b.data)}},postMessage:function(a){a.sender=b;
a=h.stringify(a);c.postMessage(a,"*")},sendHostMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:b})},sendGlobalMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"global",name:a,data:b})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var e=window.addEventListener?window.addEventListener:window.attachEvent,h=window.addEventListener?"message":"onmessage";if(!e)throw Error("No event support.");e(h,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(e,h){var b={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:require("bean"),debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)},modules:{},strings:{translations:{}}};b.strings.get=_.bind(function(b){var c=this.translations[b];return c!==h?c:b},b.strings);b.interpolate=function(b,c){return b.replace(/%\(\w+\)s/g,
function(a){var a=a.slice(2,-2),d="";a in c?d=c[a]!==h&&c[a]!==null?c[a].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+a+"` not found in context for: ",b);return d})};b.addBlocks=function(){return function(b){b(DISQUS)}};b.templateGlobals={urls:DISQUS.use("urls"),sso:null,gettext:b.strings.get};e.gettext=_.bind(b.strings.get,b.strings);b.renderDtplBlock=function(c,g){return DISQUS.blocks[c](b.templateGlobals,g)};b.renderHandlebarsBlock=function(c,g){var a="",a=e.Handlebars,g=g||{};if(a.partials.hasOwnProperty(c))a=
a.partials[c](g,{data:b.templateGlobals});else return b.renderDtplBlock(c,g);return a};b.useHandlebars=function(){var b=!1;try{b=DISQUS.next&&DISQUS.next.views.Lounge.getInstance().forum.get("settings").useHandlebars}catch(c){}return b};b.renderBlock=function(){var c=b.useHandlebars();b.renderBlock=c?b.renderHandlebarsBlock:b.renderDtplBlock;c&&e.Handlebars.lounge&&e.Handlebars.lounge.templates();return b.renderBlock.apply(this,arguments)};b.assureOffset=function(b){return b.indexOf("+")>=0?b:b+"+00:00"};
var c=b.Builder=function(){this.accum=[]};_.extend(c.prototype,{put:function(b){this.accum.push(b)},esc:function(b){return String(b).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});return b});
DISQUS.define("urls",function(){var e=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",h=encodeURIComponent(document.referrer),b={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1366930222",translations:"http://mediacdn.disqus.com/1366930222/build/lang",loading:"http://mediacdn.disqus.com/1366930222/html/simple-loading.html",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
h,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1366930222/img/next/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1366930222"+e};window.location.protocol===
"https:"&&(b=_.extend(b,{root:"",media:"",translations:"https://securecdn.disqus.com/1366930222/build/lang",loading:"/html/simple-loading.html",api:b.apiSecure,logout:"https://disqus.com/logout/?redirect="+h,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/img/next/noavatar92.png"},linkAffiliatorClient:""+
e}));return b});
DISQUS.define("api",function(){function e(b){function f(a){var e=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,e.length)===e&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId===g&&(e=a.code===0?b.success:b.error,delete a.requestId,(e||function(){})(a),document.body.removeChild(h),document.body.removeChild(d),$(window).off("message",f)))}var g=_.uniqueId("ft_"),a=document.createElement("div"),d=document.createElement("form"),e="frame_"+g,h;a.innerHTML='<iframe name="'+e+'"></iframe>';
h=a.childNodes[0];d.target=e;d.action=b.url.replace(".json",".pm");d.method=b.method||"GET";b.data=_.extend(b.data,{callback:g,referrer:document.referrer});_.each(b.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;d.appendChild(c)})});$(window).on("message",f);document.body.appendChild(h);document.body.appendChild(d);d.submit()}function h(c){c=_.defaults(c,b);c.data=c.data||
{};c.data.api_key=DISQUS.apiKey;return $.ajax(c)}var b={};return{defaults:function(c){var f,e,a;for(f in c)e=c[f],a=b[f],_.isObject(e)&&_.isObject(a)?_.extend(a,e):b[f]=e},headers:function(c){c=_.extend({},b.headers,c);b.headers=_.pick(c,_.map(c,function(b,c){if(b)return c}));return b.headers},getURL:function(b,e){e=e||{};if(e.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:h,call:function(b,f){f=f||{};f.url=DISQUS.api.getURL(b,{secure:f.secure});
f.data=_.extend(f.data||{},{api_key:DISQUS.apiKey});return(f.secure?e:h)(f)}}});(function(e){var h=DISQUS.Bus,b=DISQUS.api.getURL("internal/switches/list.jsonp");e.switches_jsonp_cb=function(b){h.sendHostMessage("switches.received",b.response)};h.on("fetch",function(c){c=c||{};c.data=c.data||{};c.data.callback="switches_jsonp_cb";c.data.api_key=DISQUS.apiKey;c=DISQUS.serialize(b,c.data,!1);DISQUS.require(c)});h.sendHostMessage("ready")})(this);